# SPDX-License-Identifier: AGPL-3.0-only
"""Small, clearly labelled REFERENCE RE-IMPLEMENTATIONS of pinned upstream formulas.

Each module names the upstream repository and commit it re-implements. Conformance
is checked against vectors computed by the upstream code itself
(tests/fixtures/upstream_reference.json, generated by tools/make_upstream_fixtures.py)
and, in CI, live against checkouts of the pinned commits. Nothing here is normative:
the upstream repositories are.
"""
