#!/usr/bin/env python3
# SPDX-License-Identifier: AGPL-3.0-only
"""Write tests/fixtures/upstream_reference.json by running the PINNED upstream code.

Usage: python3 tools/make_upstream_fixtures.py --upstream DIR
DIR must contain one checkout per repository in PINS.json, each at its pinned commit
(the script refuses otherwise). Requires NumPy. The expected values are produced by the
upstream code, not by spark_membrane, so tests/test_upstream_reference.py is an external check.
"""
from __future__ import annotations

import argparse
import json
import platform
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from upstream_harness import ROOT, pinned_commits, run_upstream, vectors  # noqa: E402

NEEDED = ("oes32-residual", "oes32_engine", "oes-resilience", "oes-telemetry-bench")


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--upstream", required=True, type=Path)
    args = ap.parse_args()
    pins = {p["name"]: p["commit"] for p in json.loads((ROOT / "PINS.json").read_text())["repositories"]}
    heads = pinned_commits(args.upstream)
    for name in NEEDED:
        if heads.get(name) != pins[name]:
            print(f"{name}: checkout is at {heads.get(name)!r}, PINS.json says {pins[name]}", file=sys.stderr)
            return 2
    import numpy
    inputs = vectors()
    outputs = run_upstream(args.upstream, inputs, ROOT / "docs" / "passport" / "frames-seed42.jsonl")
    fixture = {
        "description": "Outputs of the PINNED upstream code on fixed SYNTHETIC inputs. Generated by tools/make_upstream_fixtures.py; not computed by spark_membrane.",
        "upstream": {name: pins[name] for name in NEEDED},
        "generator_environment": {"python": platform.python_version(), "numpy": numpy.__version__},
        "inputs": inputs,
        "outputs": outputs,
    }
    path = ROOT / "tests" / "fixtures" / "upstream_reference.json"
    path.write_text(json.dumps(fixture, indent=None, separators=(",", ":"), sort_keys=True) + "\n", encoding="utf-8")
    print(f"wrote {path.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
