# SPDX-License-Identifier: AGPL-3.0-only
"""Evidence passport for a demo run, in the style of sparkainlp-x/evidence-passport.

``build_manifest`` writes an evidence-passport schema-v1 run manifest (CI validates it with the
upstream ``evidence_passport.py validate`` at the pinned commit). ``render_html`` produces a
static, script-free HTML passport. A matching hash shows only that a listed file is
byte-for-byte consistent with its recorded digest; it proves nothing about authorship, time or
validity.
"""
from __future__ import annotations

import html
from typing import Any

from . import BANNER, __version__
from .claims import assert_clean

UPSTREAM = "sparkainlp-x/evidence-passport@e275bb04064c02fb39c7d96f1aa66f7508f0cdda"


def _metric(name: str, value: float | int | None, unit: str, note: str | None = None) -> dict[str, Any]:
    m: dict[str, Any] = {"name": name, "value": value, "unit": unit}
    if note:
        m["note"] = note
    return m


def build_manifest(results: dict[str, Any], artifacts: list[dict[str, str]]) -> dict[str, Any]:
    s = results["stream"]
    c = s["counts"]
    scored = [o for o in s["outcomes"] if o["frame_index"] >= s["unscored_warmup_frames"]]
    fired = {fam: sum(1 for o in scored if o["engine_families"][fam] == "FIRED") for fam in
             ("residual", "sidecar", "weighted", "maxabs", "ewma", "cusum")}
    p = results["protocol"]
    bus = results["bus512"]
    cal = s["baseline_calibration"]
    scope = (f"synthetic native-32 stream, seed {results['seed']} ({s['frames']} frames, all audited; "
             f"EWMA/CUSUM calibrated on a separate {cal['calibration_frames']}-frame stream)")
    return {
        "schema_version": 1,
        "run_id": f"spark-membrane-demo-seed{results['seed']}",
        "project": {
            "name": "spark-membrane",
            "version": __version__,
            "source_url": "https://github.com/sparkainlp-x/spark-membrane",
            "source_note": "Generated by `python3 -m spark_membrane build-docs`; the manifest lives inside the commit it describes, so code.commit is null. Upstream repositories are pinned in PINS.json.",
        },
        "evidence_class": "synthetic",
        "dataset": {
            "name": f"Seeded synthetic native-32 stream and 512-channel bus (seed {results['seed']})",
            "kind": "synthetic telemetry-like replay generated by spark_membrane/demo.py",
            "description": "Uniform noise of +/-0.01 around a zero reference with injected single-channel spikes, a two-channel fault, a slow common drift and a global shift; a separate event-free calibration stream from the same noise model (never audited); plus 16 native-32 blocks (512 channels, no resampling) with one spike in block 11. No real telemetry.",
            "source_url": None,
        },
        "code": {"version": __version__, "commit": None},
        "seed": results["seed"],
        "protocol": {
            "name": p["protocol_id"],
            "version": "2",
            "sha256": p["sha256"],
            "locked_at": "2026-10-05T21:30:00-04:00 (self-declared)",
            "lock_commit": None,
            "description": "UNCALIBRATED placeholders (docs/PROTOCOL.md). Gating: protocol hash, oes32-residual R > 0.08 latches, oes32_engine Profile A (tau 0.08, odd sector antisymmetric), oes-resilience weighted score >= 0.50 alarms. Advisory: max-abs 0.50, EWMA (lambda 0.2) 3.0, CUSUM (k 0.5) 5.0, standardized on a separate 64-frame calibration stream, restart after alarm. Explorer cap |delta| <= 0.25, 16 seeded candidates, one index.",
        },
        "baselines": ["maxabs (advisory)", "ewma (advisory)", "cusum (advisory)"],
        "results": [
            {"scope": scope, "method": "membrane T=0 audit (gating conjunction)", "metrics": [
                _metric("ACCEPT frames", c["accept"], "frames"),
                _metric("LATCH frames", c["latch"], "frames"),
                _metric("frames with engine disagreement", c["engine_disagreement"], "frames",
                        "families compared: residual, sidecar, weighted, maxabs, ewma, cusum")]},
            {"scope": scope, "method": "explorer (seeded one-index delta, simulation only)", "metrics": [
                _metric("REPAIRED_IN_SIM", c["repaired_in_sim"], "frames", "a capped single-index synthetic edit passed the audit; original kept, nothing committed"),
                _metric("LATCH_HELD", c["latch_held"], "frames")]},
            {"scope": f"{scope}; scored frames only", "method": "per-engine firing counts (not combined)", "metrics": [
                _metric(f"{k} fired", v, "frames") for k, v in fired.items()]},
            {"scope": "synthetic 512-channel bus (16 native-32 blocks), last frame", "method": "membrane T=0 audit per block", "metrics": [
                _metric("latched blocks", sum(1 for r in bus["rows"] if r["verdict"] != "ACCEPT"), "blocks"),
                _metric("accepted blocks", sum(1 for r in bus["rows"] if r["verdict"] == "ACCEPT"), "blocks")]},
        ],
        "result_label": "synthetic_example",
        "interpretation": "This run shows how the console behaves on invented frames: which gating check latched, at which index, where the engines disagreed, and whether a capped one-index simulated edit would pass. It says nothing about real telemetry, about any detector's superiority, or about any physical system.",
        "limitations": [
            "All frames are SYNTHETIC; every threshold and cap is UNCALIBRATED (upstream defaults or author choices), not a recommendation.",
            "Engines are small reference re-implementations tested against the pinned upstream code, not the upstream packages themselves.",
            "EWMA/CUSUM are advisory; their restart-after-alarm rule is an author choice (upstream defines none). On the slow drift only they fire while the gate ACCEPTs.",
            "REPAIRED_IN_SIM is a simulation verdict; the capability gate refuses to commit any explorer proposal.",
            "The shield gate applies the oes32-membrane-shield role table; Ed25519 capability signatures are verified only when the optional [shield] extra (cryptography) is installed, otherwise signed requests are refused.",
            "A matching SHA-256 shows byte consistency only; locked_at is self-declared.",
        ],
        "artifacts": artifacts,
    }


def render_html(manifest: dict[str, Any]) -> str:
    e = html.escape
    rows = []
    for r in manifest["results"]:
        for m in r["metrics"]:
            note = f" <span class=note>({e(m['note'])})</span>" if m.get("note") else ""
            rows.append(f"<tr><td>{e(r['scope'])}</td><td>{e(r['method'])}</td><td>{e(m['name'])}{note}</td>"
                        f"<td class=num>{e(str(m['value']))} {e(m['unit'])}</td></tr>")
    arts = "".join(f"<li><a href=\"{e(a['path'])}\"><code>{e(a['path'])}</code></a> ({e(a['role'])}) "
                   f"SHA-256 <code>{e(a['sha256'])}</code></li>" for a in manifest["artifacts"])
    lims = "".join(f"<li>{e(x)}</li>" for x in manifest["limitations"])
    p = manifest["protocol"]
    doc = f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8"/>
<meta name="viewport" content="width=device-width, initial-scale=1"/>
<title>Evidence passport: {e(manifest['run_id'])}</title>
<style>
body{{font-family:system-ui,sans-serif;max-width:60rem;margin:0 auto;padding:0 1rem 3rem;line-height:1.5;color:#1a1a1a}}
.banner{{position:sticky;top:0;background:#6b3900;color:#fff;padding:.6rem 1rem;margin:0 -1rem 1rem;font-weight:700}}
table{{border-collapse:collapse;width:100%;font-size:.92rem}} td,th{{border:1px solid #ddd;padding:.35rem .5rem;vertical-align:top}}
th{{background:#f4f4f4;text-align:left}} .num{{text-align:right;white-space:nowrap}} .note{{color:#555;font-size:.85em}}
.card{{border-left:4px solid #b45309;background:#fffbeb;padding:.6rem 1rem;margin:1rem 0}} code{{font-size:.85em;word-break:break-all}}
</style>
</head>
<body>
<div class="banner">SYNTHETIC EXAMPLE: {e(BANNER)}</div>
<h1>Evidence passport: <code>{e(manifest['run_id'])}</code></h1>
<p>Rendered in the style of <a href="https://github.com/sparkainlp-x/evidence-passport">evidence-passport</a> from
<a href="manifest.json">manifest.json</a> (schema v1). Result label: <strong>{e(manifest['result_label'].replace('_', ' '))}</strong>;
evidence class: <strong>{e(manifest['evidence_class'])}</strong>; seed {e(str(manifest['seed']))}.</p>
<div class="card"><strong>Interpretation.</strong> {e(manifest['interpretation'])}</div>
<h2>Protocol</h2>
<p><code>{e(p['name'])}</code> v{e(p['version'])}, SHA-256 <code>{e(p['sha256'])}</code>, locked at {e(p['locked_at'])}.</p>
<p>{e(p['description'])}</p>
<h2>Results (each metric reported separately; nothing is combined into a score)</h2>
<table><tr><th>Scope</th><th>Method</th><th>Metric</th><th>Value</th></tr>{''.join(rows)}</table>
<h2>Limitations</h2><ul>{lims}</ul>
<h2>Artifacts</h2><ul>{arts}</ul>
<p class="note">A matching hash shows only that a listed file is byte-for-byte consistent with the digest recorded here.
It does not prove who created a file, when a protocol existed, or whether a method is valid.</p>
<p><a href="../index.html">Back to spark-membrane</a></p>
</body>
</html>
"""
    return assert_clean(doc, "passport HTML")


__all__ = ["build_manifest", "render_html", "UPSTREAM"]
